apiVersion: 1

contactPoints:
  - orgId: 1
    name: kwork-ops-telegram
    receivers:
      - uid: kwork-ops-telegram
        type: telegram
        disableResolveMessage: false
        settings:
          bottoken: $__env{GRAFANA_TELEGRAM_BOT_TOKEN}
          chatid: $__env{GRAFANA_TELEGRAM_CHAT_ID}
          parse_mode: HTML
  - orgId: 1
    name: kwork-ops-slack
    receivers:
      - uid: kwork-ops-slack
        type: slack
        disableResolveMessage: false
        settings:
          url: $__env{GRAFANA_SLACK_WEBHOOK_URL}
          title: '{{ .CommonLabels.alertname }}'
          text: '{{ .CommonAnnotations.description }}'
