apiVersion: 1

policies:
  - orgId: 1
    receiver: kwork-ops-telegram
    group_by: ['alertname', 'team']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    matchers:
      - label: team
        match: =
        value: ops
    continue: true
  - orgId: 1
    receiver: kwork-ops-slack
    group_by: ['alertname', 'team']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    matchers:
      - label: team
        match: =
        value: ops
